# Generated by Django 6.0.2 on 2026-02-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="totla_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
