# Generated by Django 6.0.2 on 2026-02-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0002_book_totla_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="totla_price",
            new_name="total_price",
        ),
    ]
